[package]
name = "gloo-webextensions"
version = "0.1.0"
authors = ["Rust and WebAssembly Working Group"]
edition = "2018"

[dependencies]
js-sys = "0.3.14"

[dependencies.serde]
version = "1.0.89"
features = ["derive"]

[dependencies.wasm-bindgen]
version = "0.2.37"
features = ["serde-serialize"]
