[package]
authors = ["Rust and WebAssembly Working Group"]
description = "A modular toolkit for Rust and WebAssembly"
edition = "2018"
license = "MIT/Apache-2.0"
name = "gloo"
readme = "README.md"
version = "0.1.0"

[dependencies]
gloo-dom = { version = "0.1.0", path = "crates/dom" }
gloo-timers = { version = "0.1.0", path = "crates/timers" }

[workspace]
members = [
    "crates/dom",
    "crates/timers",
    "examples/smartcounter"
]
